# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RxIgfqnXBG8VX1om_tUZlZ2SNCjOHQ_m
"""

pip install python-docx

from PIL import Image
from numpy import asarray
import numpy as np
from docx import Document
from docx.shared import RGBColor
from docx.shared import Pt

image_path = "images.jpeg"
image = Image.open(image_path)
lines=[]
text=""
with open("text.txt") as file:
    lines = [line.strip() for line in file]
for i in lines:
  text+=i
a =asarray(image)

doc = Document()
para=doc.add_paragraph()
l=list(text)

x=0
# Loop over the rows and columns of a 2D array a
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        # Add a run of text to a paragraph object para
        run = para.add_run(text[(x+j) % len(text)])
        # Set the font color and size of the run based on the values in a
        color = tuple(int(c) for c in a[i][j])
        run.font.color.rgb = RGBColor(*color)
        run.font.size = Pt(1)
    # Update the starting index of the text string for the next row
    x += a.shape[1]
    # Add a line break to the paragraph after each row
    para.add_run('\n')


doc.save("output_B20CS047.docx")